witnet/witnet-solidity-bridge

contracts/BlockRelay.sol, contracts/WitnetBridgeInterface.sol, test/block_relay.js, test/rad_error.js, test/wbi.js
Fix small errors in the modifiers in blockExists and blockDoesNotExist.
Exchanges the messages between them.
=> fix(block_relay): wrong message in modifiers

package.json, test/using_witnet.js, test/using_witnet_bytes.js, truffle-config.js, yarn.lock
We discovered 2 problems:
1. Modify tests `before` methods to make them start from a clean state.
2. `truffly-plugin-verify` dependency was failing while installing from `npm`.
Co-authored-by: Gorka Irazoqui <gorka.irazoki@gmail.com>
Closes #42
=> fix: update before methods to use new contracts

README.md, contracts/ActiveBridgeSetLib.sol, contracts/NewBlockRelay.sol, migrations/5_deploy_new_block_relay.js, test/helpers/NewBRTestHelper.sol, test/new_block_relay.js
- Adds NewBlockRelay.sol contract with proposing blocks function:
- Only ABS members can propose blocks
- Only blocks for the previous epoch are accepted
- Posts the block when proposal epoch changes and when consensus is achieved
- Finalized blocks automatically finalize previous blocks if they were not
- Adds tests to the new Block Relay with a Helper contract.
- Adds comments in README.md
- Adds absMemebership function in ActiveBridgeSetlibrary.sol.
This PR closes #36 #43 #39
=> feat(block_relay): add new contract and tests

package.json, yarn.lock
- Bring back the truffle-plugin-verify to verify smart contracts as dependencies seem to be fixed
=> chore: bring back truffle verify plugin

contracts/WitnetBridgeInterface.sol, contracts/mocks/MockBlockRelay.sol, package.json
Rename in package.json and in contracts that import contracts from it:
block-relay ==> witnet-ethereum-block-relay
Closes #61
=> fix: rename block-relay in package.json

.gitignore, contracts/ActiveBridgeSetLib.sol, contracts/BufferLib.sol, contracts/CBOR.sol, contracts/Migrations.sol, contracts/Request.sol, contracts/SafeMath.sol, contracts/UsingWitnet.sol, contracts/UsingWitnetBytes.sol, contracts/Witnet.sol, contracts/WitnetRequestsBoard.sol, contracts/WitnetRequestsBoardInterface.sol, contracts/WitnetRequestsBoardProxy.sol, contracts/mocks/MockBlockRelay.sol, contracts/mocks/MockWitnetRequestsBoard.sol, package.json, test/TestActiveBridgeSet.sol, test/TestBuffer.sol, test/TestCBOR.sol, test/Witnet.sol, test/helpers/UsingWitnetBytesTestHelper.sol, test/helpers/UsingWitnetTestHelper.sol, test/helpers/WitnetRequestsBoardTestHelper.sol, test/helpers/WrbProxyTestHelper.sol, test/test_instances/WitnetRequestsBoardV1.sol, test/test_instances/WitnetRequestsBoardV2.sol, test/test_instances/WitnetRequestsBoardV3.sol, test/using_witnet.js, truffle-config.js
Fix errors from code review #68 : 
```
·----------------------------------------------·--------------·-------·
|                Error Type                    |  Occurences  | FIXED |
······································································|
| Unsafe array's length manipulation           |           2  |     0 |
······································································|
| Multiplication after division                |           1  |     0 |
······································································|
| Extra gas consumption                        |           3  |     3 |
······································································|
| Costly loop                                  |           6  |     0 | …
```
=> [WIP] chore: update versions and fix code review errors

contracts/WitnetRequestsBoard.sol, test/wrb.js
this PR checks the length of the posted result and reverts if it is zero. This avoids potential re-entrancy attacks if the block relay accepts the PoI.
This PR closes #75
=> fix: check posted result length

contracts/mocks/MockWitnetRequestsBoard.sol
This PR just adds push dr hash functionality to the mocked witnet requests board. This is necessary to be able to handle tests from UsingWitnet.
=> fix: add report dr hash needed by using witnet

README.md, contracts/WitnetRequestsBoard.sol, test/using_witnet.js, test/using_witnet_bytes.js, test/wrb.js
This PR implements the absMember modifier in WitnetRequestBoard.sol when calling reportResult. 
Now only the members of the active bridge set are able to report results, before there were no barriers to call this function.
The tests wrb.js, using_witnet.js and using_witnet_bytes.js have been adapted to the new modifier.
Closes #74
=> Implement only ABS members can report results

contracts/ActiveBridgeSetLib.sol
In the ActiveBridgeSetLib.sol there was  an Integer Overflow vulnerability detected by Red4Sec.
It has been solved by updating the "id" type to uint256, same type as "epochIdsLength".
This PR closes #82
=> fix: change id type to uint256

.soliumignore, contracts/UsingWitnet.sol, contracts/WitnetRequestsBoard.sol, test/helpers/UsingWitnetTestHelper.sol, test/using_witnet.js, test/wrb.js
This PR prevents burning user funds due to non-existent checks in post request and upgrade request  functions, located in both `UsingWitnet` and `WitnetRequestsBoard` contracts.
To discuss what to do with `UsingWitnetBytes` as it has not been properly maintained:
- lacks of some modifiers (e.g. `witnetRequestAccepted`)
- deviates from function signatures used in `UsingWitnet.sol`
Supersedes #73
=> fix: preventing burning user funds

contracts/WitnetRequestsBoard.sol, test/using_witnet.js
Closes #103
Witnet-ethereum-bridge\contracts\ActiveBridgeSetLib.sol:65-67 - The variable "i"
should be uint256 to maintain the code styling -> Fixed by #82
=> fix: improve code readibility issues

contracts/ActiveBridgeSetLib.sol, contracts/BufferLib.sol, contracts/CBOR.sol, contracts/Witnet.sol, contracts/WitnetRequestsBoard.sol
Multiple gas optimizations as suggested by red4sec.
Only three of their suggestions are NOT included in this PR. Explanations below:
- **Witnet-ethereum-bridge\contracts\Witnet.sol:432-433 - Could be uint16 instead of uint64.**
It would be antiergonomic to force the caller to do the uint64 → uint16 trimming, because this is always used on uint64 values because that's the API of our CBOR arrays.
- **Witnet-ethereum-bridge\contracts\Witnet.sol:299-300 - Use bytes instead of uint64.**
It is a convention in Witnet that errors are returned as CBOR arrays containing unsigned integers. As the only unsigned integer type currently supported is `uint64`, we are force to use that.
If you want the raw bytes representation of the error, you already have `result.cborValue.buffer.data`
- …
=> Gas optimizations

contracts/WitnetRequestsBoard.sol, test/wrb.js
This PR adds a modifier in `ReportDataRequestInclusion` so that reverts if the data request has not been claimed. It also adds a test.
Closes #101
=> Claim verification

.soliumignore, contracts/BufferLib.sol, contracts/WitnetRequestsBoard.sol, test/TestBuffer.sol, test/wrb.js
This PR adds some checks that were not existent in the smart contracts. Some of which have not been fixed:
Witnet-ethereum-block-relay\contracts\CentralizedBlockRelay.sol:156-157
In flushSlot() function, it is not verified that values are the expected. It should be verified -> **Non-existent (probably a mistake in the report)** 
Witnet-ethereum-bridge\contracts\ActiveBridgeSetLib.sol:50-51
In flushSlot() function, it is not verified that values are the expected. It should be verified
that the epoch is the consecutive or the same as the last inserted. -> **Verified in UpdateABS from WRB**
• Witnet-ethereum-bridge\contracts\WitnetRequestsBoardProxy.sol:120-125
When exiting for loop, instead of returning the default values. We recommend including a
revert() in order to avoid returning …
=> fix: add non-existent checks in libraries and WRB

contracts/WitnetRequestsBoardProxy.sol
The `WitnetRequestBoardProxy`  contract was not using a fixed solidity compiler version as it should.
=> fix: use 0.6.4 solidity version

contracts/ActiveBridgeSetLib.sol, contracts/BufferLib.sol
This PR avoids overflows to occur in:
- BufferLib.sol
- ActiveBridgeSetLib.sol
Closes #98 and #99
=> Avoid overflow

contracts/Witnet.sol
self explanatory.
Closes 11.3 from the red4sec audit report.
=> docs: warn about possible errors in asErrorMessage

contracts/ActiveBridgeSetLib.sol, test/TestActiveBridgeSet.sol, test/wrb.js
This issue moves checking whether the block number provided is higher than the last one inserted to the ABS library.Closes issue 13.10 from the security audit
=> fix: update ABS activity checks

contracts/CBOR.sol, contracts/Witnet.sol, test/TestWitnet.sol
This PR checks the case of having an error message with length 0 in the functions `asErrorCode` and `asErrorMessage`.
Additionally, we updated the solidity version of the contracts `CBOR` and `Witnet` to a fixed one `0.6.8`. There should not be a problem with the solidity versions as the Witnet consumer contraacts will inherit `UsingWitnet` (by `is UsingWitnet`) and the `CBOR` and `Witnet` contracts will be just linked. :smile: 
This PR fixes the issue identified by Red4Sec 13.11 (closes #118).
=> fix: check if error code length is zero

contracts/WitnetRequestsBoard.sol, test/using_witnet.js, test/wrb.js
This PR solves the problem found by Red4sec #88.  The idea is to check the epoch when reporting a data request, reporting the data request inclusion and reporting the result. It is required that each of the just mentioned functions are executed chronologically.
This PR adds:
- epoch field in DataRequest struct
- require in reportDataRequestInclusion
- require in reportResult
- tests in wrb.js
Fix #88
=> Add epoch condition in wrb to avoid replay poi attack

README.md, contracts/UsingWitnet.sol, contracts/WitnetRequestsBoard.sol, contracts/WitnetRequestsBoardInterface.sol, contracts/WitnetRequestsBoardProxy.sol, contracts/mocks/MockBlockRelay.sol, contracts/mocks/MockWitnetRequestsBoard.sol, package.json, test/helpers/UsingWitnetTestHelper.sol, test/test_instances/WitnetRequestsBoardV1.sol, test/test_instances/WitnetRequestsBoardV2.sol, test/test_instances/WitnetRequestsBoardV3.sol, test/using_witnet.js, test/wrb.js, test/wrb_gas.js, test/wrb_proxy.js
This PR expands on https://github.com/witnet/witnet-ethereum-block-relay/pull/29 to be able to pay the block relayer. The block reward is divided in two, one for the inclusion and one for the reward.
Missing things:
- Upgrade Request should also include an upgrade for the block relay reward.
- More extensive testing
=> Pay block reward

contracts/WitnetRequestsBoard.sol, test/using_witnet.js, test/wrb.js, test/wrb_gas.js
This PR:
- Stores the gas price set by the requestor in the DR information structure.
- Adds a getter to retrieve such a gas price.
- Rejects the DR if the rewards do not match the expected gas times the gas price set.
=> Store gas price per dr

README.md, migrations/witnet.addresses.json, migrations/witnet.settings.js, package.json
Deploy latest version into all supported testnets:
=> Chore: Generate 0.4.1 addresses

contracts/impls/trustable/WitnetRequestBoardTrustableBoba.sol, migrations/scripts/1_deploy_wrb.js, migrations/witnet.addresses.json, migrations/witnet.settings.js
Moreover, let constructor parameters may also be set per network: network > realm > default.
=> Fix(TrustableBoba): read `reportResult` gas estimation from immutable

contracts/impls/trustable/WitnetRequestBoardTrustableBoba.sol, contracts/impls/trustable/WitnetRequestBoardTrustableDefault.sol, migrations/scripts/1_deploy_wrb.js, migrations/witnet.addresses.json, migrations/witnet.settings.js, package.json, test/helpers/WitnetRequestBoardTestHelper.sol
- From this version on, TrustableDefault will read resportResult gas limit estimation from immutable
- Add **CELO.alfajores** configs and deployed addresses
=> Feat: Add support to CELO chains

contracts/libs/WitnetBuffer.sol, migrations/witnet.addresses.js, package.json, test/TestWitnetBuffer.sol, truffle-config.js
When copying 32-byte length bytes array.
=> Fix: Avoid unhandled revert in WitnetBuffer.memcpy(..)

contracts/examples/WitnetPriceRouter.sol
- Shorter to code
- Simpler to remember
- Big enough to avoid collisions within same WitnetPriceRouter
```solidity
import "witnet-solidity-bridge/contracts/interfaces/IWitnetPriceRouter.sol`
contract MyContract {
function lastBtcUsdValue() external view returns (int, uint, uint) {
return IWitnetPriceRouter(<0x-address of WitnetPriceRouter>).valueFor(bytes32(0x24beead4));
}
function lastEthUsdValue() external view returns (int, uint, uint) {
return IWitnetPriceRouter(<0x-address of WitnetPriceRouter>).valueFor(bytes32(0x3d15f701));
}
}
```
=> Feat: Reduce pricefeed ids to 4 bytes
