contracts/Witnet.sol
test/Witnet.sol

This is a follow-up to #34, solving #30 and #44

Missing commits RE: Radon errors

---

contracts/WBIInterface.sol
contracts/WitnetBridgeInterface.sol
contracts/mocks/MockWitnetBridgeInterface.sol
yarn.lock

- Creates WBI Interface
- Creates mocked WBI contract
This PR closes #53

Implement Mocked WBI

---

migrations/2_deploy_block_relay.js
migrations/3_deploy_wbi.js
migrations/3_deploy_wrb.js

Migrations were not updated with:
- last renaming from WBI to WRB
- include WRB proxy

fix: add wrb proxy to migrations

---

.gitignore
README.md
contracts/UsingWitnet.sol
contracts/WitnetRequestsBoard.sol

Update of methods and their signatures.

docs: update README with latest changes

---

migrations/addresses.json

Update contract addresses in rinkeby and goerli in _addresses.json_.

fix: update addresses

---

contracts/CBOR.sol

fix: amend readLength revert message

---

contracts/WitnetRequestsBoard.sol

This PR modifies the state upon which `reportDrInclusion` and `reportResult` depend before the externals calls are made

fix: read modifier dependent state before external calls

---

contracts/WitnetRequestsBoardProxy.sol
test/wrb_proxy.js

Requires the id inserted to be greater than 0

fix: check id is non-zero in getController

---

contracts/ActiveBridgeSetLib.sol
contracts/BufferLib.sol
contracts/CBOR.sol
contracts/Migrations.sol
contracts/Request.sol
contracts/UsingWitnet.sol
contracts/Witnet.sol
contracts/WitnetRequestsBoard.sol
contracts/WitnetRequestsBoardInterface.sol
contracts/WitnetRequestsBoardProxy.sol
contracts/mocks/MockBlockRelay.sol
contracts/mocks/MockWitnetRequestsBoard.sol
flattened-config.js
test/TestActiveBridgeSet.sol
test/TestBuffer.sol
test/TestCBOR.sol
test/TestWitnet.sol
test/helpers/UsingWitnetTestHelper.sol
test/helpers/WitnetRequestsBoardTestHelper.sol
test/helpers/WrbProxyTestHelper.sol
test/test_instances/WitnetRequestsBoardV1.sol
test/test_instances/WitnetRequestsBoardV2.sol
test/test_instances/WitnetRequestsBoardV3.sol
truffle-config.js

This PR mitigates issue 10 of the Red4Sec issue.

chore: update solidity to 0.6.8

---

contracts/WitnetRequestsBoard.sol
test/wrb.js

feat: add getter for data request claimer pkh

---

contracts/WitnetRequestsBoardProxy.sol
test/TestActiveBridgeSet.sol
test/TestBuffer.sol

fix(WRBProxy): correct visibility

---

contracts/WitnetRequestsBoard.sol
contracts/mocks/MockBlockRelay.sol
test/wrb_gas.js

Return the block reward to the requestor in case of the relayer was already paid

---

contracts/CBOR.sol
contracts/Witnet.sol
contracts/WitnetRequestBoard.sol
contracts/WitnetRequestBoardProxy.sol
test/TestCBOR.sol
test/helpers/WrbProxyTestHelper.sol

This PR includes:
- fix(wrb): add isInCommittee mapping WRB
- refactor(proxy): remove redundant wrb address
- test(proxy): update tests
- feat(cbor): add `decodeBool` function
- fix(cbor): return `int32[]` instead of `int128[]` on `decodeFixed16Array` function

Add audit changes

---

README.md
contracts/BufferLib.sol
contracts/Migrations.old
contracts/Request.sol
contracts/Witnet.sol
contracts/WitnetRequestBoard.sol
contracts/WitnetRequestBoardInterface.sol
contracts/WitnetRequestBoardProxy.sol
migrations/1_initial_migration.old
test/TestBuffer.sol
test/TestCBOR.sol
test/TestWitnet.sol
test/helpers/RequestTestHelper.sol

Add error messages for bridgeErrors

feat: add message for bridge radon errors

---

README.md
contracts/impls/WitnetProxy.sol
migrations/scripts/1_deploy_wrb.js
migrations/witnet.addresses.json
migrations/witnet.settings.js
package.json

Feat: Add support to CELO providers

---

README.md
contracts/UsingWitnet.sol
package.json
test/helpers/UsingWitnetTestHelper.sol
test/using_witnet.js

Feat(UsingWitnet): self-estimate reward values when posting or upgrading requests

---

migrations/witnet.addresses.json
migrations/witnet.settings.js

Feat: Add support to Moonbeam networks

---

migrations/witnet.addresses.json
migrations/witnet.settings.js

Close https://github.com/witnet/internal/issues/175.

Chore: Deploy on Avalanche Mainnet

---

migrations/witnet.addresses.json
migrations/witnet.settings.js

Feat: Add support to Cronos chains

---

migrations/witnet.addresses.json
migrations/witnet.settings.js

- WitnetRequestBoardTrustableDefault in all testnets
- WitnetRandomness in all testnets but Harmony
Close #225.

Chore: Update testnets addresses to 0.5.6

---

migrations/witnet.addresses.json
migrations/witnet.settings.js

Close https://github.com/witnet/internal/issues/177.

Chore: Deploy on Cronos Mainnet

---

migrations/witnet.addresses.json
migrations/witnet.settings.js

Both testnet and mainnet.
Close #223.

Chore: Deploy on Conflux eSpace

---

migrations/witnet.addresses.json

- WitnetRequestBoardTrustableDefault
- WitnetRandomness
Close #240.

Chore: Upgrade WSB to v0.5.6 on mainnets

---

migrations/witnet.settings.js

See https://github.com/witnet/internal/issues/186#issuecomment-1123553140.

Fix: Witnet reward estimation on WRB Boba implementation

---

migrations/witnet.addresses.json
migrations/witnet.settings.js

Chore: Deploy on kava mainnet

---

migrations/witnet.addresses.json
migrations/witnet.settings.js
package.json

Feat: Deploy on Cube Chain testnet

---

migrations/witnet.addresses.json
migrations/witnet.settings.js

Chore: Attend chore ops during week #220727

---

contracts/impls/trustable/WitnetRequestBoardTrustableDefault.sol
contracts/impls/trustable/WitnetRequestBoardTrustableReef.sol
migrations/witnet.addresses.json
migrations/witnet.settings.js

And deploy whole stack on testnet.

feat: add support to Reef chain 

---

.eslintrc
contracts/impls/trustable/WitnetRequestBoardTrustableOvm2.sol
migrations/scripts/1_deploy_wrb.js
migrations/witnet.settings.js
package.json
test/examples/RandomnessBareMinimal.sol
test/helpers/UsingWitnetTestHelper.sol
test/using_witnet.test.js
test/witnet_randomness.test.js
test/wrb.test.js

After breaking down due to latest Node.js upgrade to v14/v16 within CI/CD workflows.
Close #244.

Fix: Upgrade tests to Truffle v5.6.2

---

migrations/witnet.settings.js

Close https://github.com/witnet/witnet-solidity-bridge/issues/361

fix: report gas limit on cronos mainnet
